package gui5;

import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class frmCandidatos extends javax.swing.JFrame {

    private int codigo=1, fila=0;
    private double puntos=0;
    
    public frmCandidatos() {
        initComponents();
        txtCodigo.setText(String.valueOf(codigo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngSexo = new javax.swing.ButtonGroup();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        rbtnHombre = new javax.swing.JRadioButton();
        rbtnMujer = new javax.swing.JRadioButton();
        lblSexo = new javax.swing.JLabel();
        lblEstudios = new javax.swing.JLabel();
        chkBachillerato = new javax.swing.JCheckBox();
        chkUniversidad = new javax.swing.JCheckBox();
        chkMaestria = new javax.swing.JCheckBox();
        chkDoctorado = new javax.swing.JCheckBox();
        lblDepartamento = new javax.swing.JLabel();
        cmbDepartamentos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCandidatos = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/iconos/registro.png")).getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigo.setText("Código");
        getContentPane().add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 21, 60, -1));

        txtCodigo.setEnabled(false);
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 18, 77, -1));

        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 52, 82, -1));

        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 49, 400, -1));

        btngSexo.add(rbtnHombre);
        rbtnHombre.setText("Hombre");
        getContentPane().add(rbtnHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 87, -1, -1));

        btngSexo.add(rbtnMujer);
        rbtnMujer.setText("Mujer");
        getContentPane().add(rbtnMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 87, -1, -1));

        lblSexo.setText("Sexo");
        getContentPane().add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 87, -1, -1));

        lblEstudios.setText("Estudios");
        getContentPane().add(lblEstudios, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 128, -1, -1));

        chkBachillerato.setText("Bachiller");
        getContentPane().add(chkBachillerato, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 120, -1, -1));

        chkUniversidad.setText("Universitario");
        getContentPane().add(chkUniversidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 151, -1, -1));

        chkMaestria.setText("Maestría");
        getContentPane().add(chkMaestria, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 120, -1, -1));

        chkDoctorado.setText("Doctorado");
        chkDoctorado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkDoctoradoItemStateChanged(evt);
            }
        });
        chkDoctorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDoctoradoActionPerformed(evt);
            }
        });
        getContentPane().add(chkDoctorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 151, -1, -1));

        lblDepartamento.setText("Departamento");
        getContentPane().add(lblDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 195, -1, -1));

        cmbDepartamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECCIONE UNO>", "AHUACHAPAN", "SONSONATE", "SANTA ANA", "LA LIBERTAD", "SAN SALVADOR", "CHALATENANGO", "LA UNIÓN", "LA PAZ", "CABAÑAS", "SAN VICENTE", "SAN MIGUEL" }));
        getContentPane().add(cmbDepartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 192, 180, -1));

        tblCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Puntos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCandidatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 510, 200));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
       char dato=evt.getKeyChar();
       String entrada=""+dato;
       if(!entrada.matches("[a-zA-ZñÑÁÉÍÓÚ ]+")){evt.consume();}
/*        if (Character.isLowerCase(c)) {
            String convert = ("" + c).toUpperCase();
            c = convert.charAt(0);
            evt.setKeyChar(c);
        }
*/
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
       char dato=evt.getKeyChar();
       String entrada=""+dato;
       if(!entrada.matches("[0-9]+")){evt.consume();}

        
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void Limpiar(){
        txtCodigo.setText("");
        txtNombre.setText("");
        btngSexo.clearSelection();
        chkBachillerato.setSelected(false);
        chkUniversidad.setSelected(false);
        chkMaestria.setSelected(false);
        chkDoctorado.setSelected(false);
        cmbDepartamentos.setSelectedIndex(0);
        txtNombre.requestFocus();
        
    }
    
    
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       
        
        if (txtNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese el nombre");
            txtNombre.requestFocus();
        }
        else if (rbtnHombre.isSelected()==false && rbtnMujer.isSelected()==false){
            JOptionPane.showMessageDialog(null, "Seleccione sexo");
            rbtnHombre.requestFocus();
        }
        
        tblCandidatos.setValueAt(txtCodigo.getText(), fila, 0);
        tblCandidatos.setValueAt(txtNombre.getText(), fila, 1);
        tblCandidatos.setValueAt(puntos, fila, 2);
        
        fila=fila+1;
        codigo=codigo+1;
        Limpiar();
        
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void chkDoctoradoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkDoctoradoItemStateChanged
        puntos=0;
        if (chkDoctorado.isSelected()){
            chkMaestria.setSelected(true);
            chkUniversidad.setSelected(true);
            chkBachillerato.setSelected(true);
        }
        else{
            chkMaestria.setSelected(false);
            chkUniversidad.setSelected(false);
            chkBachillerato.setSelected(false);
        }
        //falta programar los otros checkbox
        if (chkBachillerato.isSelected()){
            puntos=puntos+5;
        }
        
        if (chkUniversidad.isSelected()){
            puntos=puntos+15;
        }
        
        if (chkMaestria.isSelected()){
            puntos=puntos+30;
        }
        
        if (chkDoctorado.isSelected()){
            puntos=puntos+50;
        }
        

        
    }//GEN-LAST:event_chkDoctoradoItemStateChanged

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
        txtCodigo.setText(String.valueOf(codigo));
        
    }//GEN-LAST:event_txtNombreFocusGained

    private void chkDoctoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDoctoradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDoctoradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCandidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCandidatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.ButtonGroup btngSexo;
    private javax.swing.JCheckBox chkBachillerato;
    private javax.swing.JCheckBox chkDoctorado;
    private javax.swing.JCheckBox chkMaestria;
    private javax.swing.JCheckBox chkUniversidad;
    private javax.swing.JComboBox<String> cmbDepartamentos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblEstudios;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JRadioButton rbtnHombre;
    private javax.swing.JRadioButton rbtnMujer;
    private javax.swing.JTable tblCandidatos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
